import { Inter } from "next/font/google";
import "./globals.css";
import  Sidebar  from "./components/Sidebar";
import { MyProvider } from "./components/MyContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NewsMania",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className} >
      <body className="bg-gray-200">
        <MyProvider>
          <Sidebar />
          {children}
        </MyProvider>
      </body>
    </html>
  );
}
