import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { MyProvider } from "./components/MyContext";
import { LikeProvider } from "./context/Contest";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NewsMania",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" className={inter.className}>
        <body className="bg-gray-200">
          <LikeProvider>
            <MyProvider>
              <Navbar />
              {children}
            </MyProvider>
          </LikeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}